name = "dj-judas"
main = "./src/worker/index.ts"
compatibility_date = "2025-04-01"
compatibility_flags = ["nodejs_compat"]
account_id = "a77e479f6736120eadd99973dbeb705e"

# ===== PERFORMANCE OPTIMIZATIONS =====
# Smart placement automatically deploys your Worker to optimal locations
[placement]
mode = "smart"

[observability]
enabled = true

upload_source_maps = true

[assets]
directory = "./dist/client"
not_found_handling = "single-page-application"

# ===== CORE BINDINGS =====
# KV Namespace for session storage
[[kv_namespaces]]
binding = "SESSIONS"
id = "b7654d69472c4e1b8eda8bbae8ee2776"

# Workers AI for product suggestions and AI features
[ai]
binding = "AI"

# D1 Database
[[d1_databases]]
binding = "DB"
database_name = "dj-judas-db"
database_id = "5b2ae7e3-cc4d-4c1e-9c14-63974347443a"


# ===== OPTIONAL ADVANCED BINDINGS =====
# R2 Object Storage for media and user assets
[[r2_buckets]]
binding = "MEDIA_BUCKET"
bucket_name = "dj-judas-media"

[[r2_buckets]]
binding = "USER_ASSETS"
bucket_name = "user-assets"

# Queue for background processing (emails, notifications)
# [[queues.producers]]
# binding = "EMAIL_QUEUE"
# queue = "email-queue"

## Durable Objects for rate limiting and session management
[[durable_objects.bindings]]
name = "RATE_LIMITER"
class_name = "RateLimiter"

[[durable_objects.bindings]]
name = "USER_SESSIONS"
class_name = "UserSession"

[[migrations]]
tag = "do-v1"
new_sqlite_classes = ["RateLimiter", "UserSession"]

# Analytics Engine for custom metrics
[[analytics_engine_datasets]]
binding = "ANALYTICS"

# Analytics Engine for custom analytics
# [[analytics_engine_datasets]]
# binding = "ANALYTICS"

# Rate limiting configuration
# [[unsafe.bindings]]
# name = "RATE_LIMITER"
# type = "ratelimit"
# namespace_id = "1"
# simple = { limit = 10, period = 60 }

# ===== ENVIRONMENT VARIABLES =====
# Local development uses localhost URLs
# Production will use vars set via `wrangler secret put` or dashboard
# After deploying, configure these in Cloudflare Dashboard:
# - MEDUSA_URL (your production Medusa backend URL)
# - CF_IMAGES_ACCOUNT_ID & CF_IMAGES_API_TOKEN (for product image uploads)
# - OPENAI_API_KEY (for AI product descriptions - optional)
# - RESEND_API_KEY or SENDGRID_API_KEY (for booking emails - optional)

[vars]
# These are dev defaults - override in production via dashboard
MEDUSA_URL = "http://localhost:9000"
SITE_URL = "http://localhost:5173"

# ===== ENVIRONMENT-SPECIFIC CONFIGURATIONS =====
# [env.production]
# vars = { ENVIRONMENT = "production", MEDUSA_URL = "https://your-medusa-backend.com" }
# route = "djlee.com/*"
#
# [env.staging]
# vars = { ENVIRONMENT = "staging" }
# route = "staging.djlee.com/*"
