name = "dj-judas"
main = "./src/worker/index.ts"
compatibility_date = "2025-04-01"
compatibility_flags = ["nodejs_compat"]
account_id = "a77e479f6736120eadd99973dbeb705e"

[observability]
enabled = true

upload_source_maps = true

[assets]
directory = "./dist/client"
not_found_handling = "single-page-application"

[ai]
binding = "AI"
