export type EventItem = {
  id: string;
  slug: string;
  title: string;
  description?: string;
  flyerUrl?: string;
  startDateTime: string;
  endDateTime?: string | null;
  venueName?: string;
  address?: string;
  city?: string;
  region?: string;
  country?: string;
  latitude?: number | null;
  longitude?: number | null;
  ticketUrl?: string;
  rsvpUrl?: string;
  priceText?: string;
  priceSummary?: string;
  tags?: string[];
  status?: 'draft' | 'published' | 'archived';
  imageMode?: 'cover' | 'contain';
  flyerWidth?: number | null;
  flyerHeight?: number | null;
  summary?: string;
  mediaEmbedUrl?: string;
  mapEmbedUrl?: string;
  faq?: { question: string; answer: string }[];
  galleryImages?: string[];
};
